language: ruby

# rvm:
# - 2.2.10
# - 2.3.8
# - 2.4.5
# - 2.5.5
# - 2.6.2
#
# cache:
#   - bundler
#
# script:
#   - bundle exec rspec

jobs:
  include:
    - &job
      stage: test runtime dependency installation
      cache: false
      install:
      - gem build dpl.gemspec
      - gem install dpl-*.gem
      before_script:
      - ls /usr/bin/python*
      script:
      - ruby -Ilib .travis/test_install.rb
      rvm: 2.2.10
    - <<: *job
      rvm: 2.3.8
    - <<: *job
      rvm: 2.4.5
    - <<: *job
      rvm: 2.5.5
    - <<: *job
      rvm: 2.6.2

# before_script:
#   - rm -f $(ruby -r rubygems -e "puts Gem.bindir")/dpl
#
# before_install:
#   - gem update bundler
#
# cache:
#   directories:
#     - vendor/cache
#     - $GEM_HOME
#     - node_modules
#
# before_cache:
#   - rm -rf $GEM_HOME/cache/dpl-*.travis.*.gem $GEM_HOME/gems/dpl-*.travis.* $GEM_HOME/specifications/dpl-*.travis.*
#   - git checkout bin/dpl
#
# env:
#   global:
#     - DPL_VERSION=$(ruby -I lib -r dpl/version.rb -e "puts Dpl::VERSION.succ + \".travis.#{ENV['TRAVIS_JOB_NUMBER']}\"")
#
# jobs:
#   include:
#     - stage: deploy
#       if: branch = master AND NOT type IN (pull_request)
#       cache: false
#       before_deploy:
#         - sed -i.bak "s/VERSION = '.*'/VERSION = '${DPL_VERSION}'/g" lib/dpl/version.rb
#         - git config user.name "travisbot"
#         - git config user.email "deploy@travis-ci.org"
#         - git add lib/dpl/version.rb
#         - git commit -m "Update Dpl::Version"
#       deploy:
#         - provider: rubygems
#           script: skip
#           edge:
#             branch: master
#           api_key:
#             secure: ZmZoDL1tilWvQrqRWDm2K4xQ5Grt9eRJzYVZPLANR0P1TM5BJBLk+UhWCWCPkkDVIBWMa5ANsiFYBxtH65Lw+uqMztSpVusk0l0LQXZGv9jMpT9445A8008U3vvfS0ke7IG8Q4bMAC7Sd6VGaiHDyZC7zmNvnqMpmVX7ShcgBME=
#           gem: dpl
#           gemspec_glob: 'dpl*.gemspec'
#           on:
#             repo: travis-ci/dpl
