language: ruby
dist: xenial

rvm:
- 2.2.7
- 2.3.4
- 2.4.1
- 2.5.5
- 2.6.2

cache:
  - bundler

script:
  - bundle exec rspec

jobs:
  include:
    - &job
      stage: test runtime dependency installation
      if: commit_message !~ /skip:test_dependencies/ AND env(SKIP_TEST_DEPENDENCIES) IS blank
      cache: false
      install:
      - gem build dpl.gemspec
      - gem install dpl-*.gem
      script:
      - .travis/test_install
      rvm: 2.2.7
    - <<: *job
      rvm: 2.3.4
    - <<: *job
      rvm: 2.4.1
    - <<: *job
      rvm: 2.5.5
    - <<: *job
      rvm: 2.6.2
