language: shell

script:
  - true

before_deploy:
  - .travis/providers/gcs/prepare

deploy:
  - provider: gcs
    edge:
      branch: dpl-2
    on:
      branch: dpl-2

    # dpl_test
    access_key_id:
      secure: "iABLcHXwe+QKA2UceW05qecEx9egQtzQWJD0laOMt3PX7NLjpF2wL76DoBHwvxFZxqN0NurAPi+JpoYXCLbCxPC0wze4mtTxrcGRJLdAQ2uAsdJi3pq+LxG3ilxMRujXoUuEyS8RY321AqmD+fcpmbrSzEttAaoWhA14ZP/n4kg="
    secret_access_key:
      secure: "a9yhXPi2v3mlkOJgOHcYoIcYv7Xu7J0hF4EF1f6Zn/ZgpQIBqqV8XKbVCMOX/UG4xbm/ZMarGQFNwdvgWPqYkAyGafffuxG8FOXlgtb39f3PexjDCgJKKVnSVJPX1+t/gMvdHPKcfA78XKIqNmKqbtw44y1GHdpsJ/be6GeVGos="
    bucket: travis-dpl-test
    local_dir: ./tmp/dpl_test
    skip_cleanup: true

# why does deploy.run not work here?
after_deploy:
  - .travis/providers/gcs/test || TRAVIS_TEST_RESULT=$?
