language: node_js

script:
  - true

before_deploy:
  - .travis/providers/npm/prepare
  - cd tmp/dpl_test

deploy:
  - provider: npm
    edge:
      branch: dpl-2
    on:
      branch: dpl-2

    email: dpl-test@travis-ci.org
    registry: https://www.myget.org/F/dpl-test/npm/
    api_key:
      secure: "RJKzq+WIewvXSvU2mTeqDn9eIM7Vq3fAvXrCdHjMGbl301ilq9IzUWhea1UJfcP0WbbF6h7oS6jl3DMKLok9Bi6A7XmT1zd3KVP5ZE8FeKVqGGS7hLk6JtymJPpVudWOb+bhcEzox52g95NHFB8/H1VFr8fSBf89NzFI7QIjBaw="
    access: public
    skip_cleanup: true

after_deploy:
  - cd ../..
  - .travis/providers/npm/test || TRAVIS_TEST_RESULT=$?
