language: ruby

env:
  # GITHUB_TOKEN=[personal access token with repo scope on travis-dpl-test]
  secure: "o7IxUSrMNTYoVqWO+LkmGn3wccPEEi9CewntdP/KGgH1g8YdDuEjZvSmSlNacEsXfibz+F3pWM1aNb3Qx5Is0fQizm0eVaAXs/4qwPZOyByzOt5QdO0PXw4BRuojc6kByW0QcsbUceyxUSFNQeWernpinlZAnblpLBjTpqbPKSw="
  # # ENGINE_YARD_API_KEY=[api key]
  # secure: "YPEP0jh93rw8jok/2d/slB4fyDX9Sx3j9uMjKy+vpkBfr6msZbejIS18zYp4F7jr28aLk2i5vnQdMTLKz9IezK5RETgPe9y+s+K4x3QXQArH4DQy2GxjkrTFfq/FKAeUJv7CK8Jlpv0goPW9SpYNB5xQa4w3Vqd8P5oTmcus0+g="

install: true
script: true

before_deploy:
  - .travis/providers/engineyard/prepare
  - export TRAVIS_COMMIT=$(GIT_DIR=tmp/dpl_test/.git git rev-parse HEAD | tr -d '\n')
  - cd tmp/dpl_test

deploy:
  - provider: engineyard
    edge:
      branch: dpl-2
    on:
      branch: dpl-2
    app: travis_dpl_test
    api_key:
      secure: "maQqcDA51oW/kVsaC6LmB7iKy2XoRxU6UStQZfGucqkryorC19RkHaKYjtEeQQORZT/Jh3+1kCMe2vXBHSsZA1lIIfIpj/HojwUGD0qeLSefDhdR2BTf78sRL+HsRE78GX8k2ORt+OQT6JcaA+rCb6/7Wk4/IygbcHHYMS+doK0="
    skip_cleanup: true

after_deploy:
  - cd ../..
  - .travis/providers/engineyard/test || TRAVIS_TEST_RESULT=$?
